version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_GNEWS_API_KEY=828eb31d0c357fa8644c9999253e2059
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/BibliotecaDigital_BD?sslmode=disable
      - PORT=8080
      - VUE_APP_GNEWS_API_KEY=828eb31d0c357fa8644c9999253e2059
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BibliotecaDigital_BD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map to 5433 to avoid conflict with local postgres if running
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d BibliotecaDigital_BD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
